#!/bin/bash

#BSUB -P STF007 
#BSUB -q debug
#BSUB -J matrix_sums_optimized
#BSUB -o matrix_sums_optimized.%J
#BSUB -nnodes 1
#BSUB -W 15

module load cuda/11.4.0
module load hip-cuda


OUTPUT=/gpfs/alpine/stf007/scratch/${USER}

jsrun -n1 -c1 -g1 -a1 nsys profile --stats=true --force-overwrite=true -o $OUTPUT/profile_data_optimized ./matrix_sums_optimized 

mv $OUTPUT/profile_data_optimized* $LS_SUBCWD