#!/bin/bash

#BSUB -P STF007 
#BSUB -q debug
#BSUB -J profiling_unoptimized
#BSUB -o profiling_output_unoptimized.%J
#BSUB -nnodes 1
#BSUB -W 15

module load cuda/11.4.0
module load hip-cuda


OUTPUT=/gpfs/alpine/stf007/scratch/${USER}

jsrun -n1 -c1 -g1 -a1 nsys profile --stats=true --force-overwrite=true -o $OUTPUT/profile_data_unoptimized ./matrix_sums_unoptimized 

cp $OUTPUT/profil* $LS_SUBCWD
